# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T09:41:53+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, ConfigDict, Field, RootModel, SecretStr, conint, constr


class ASConfigMaxConcurrency(RootModel[conint(ge=1, le=200)]):
    root: conint(ge=1, le=200)


class ASConfigMaxSize(RootModel[conint(ge=1)]):
    root: conint(ge=1)


class ASConfigMinSize(RootModel[conint(ge=1, le=25)]):
    root: conint(ge=1, le=25)


class AppRunnerResourceArn(
    RootModel[
        constr(
            pattern=r'arn:aws(-[\w]+)*:[a-z0-9-\\.]{0,63}:[a-z0-9-\\.]{0,63}:[0-9]{12}:(\w|\/|-){1,1011}',
            min_length=1,
            max_length=1011,
        )
    ]
):
    root: constr(
        pattern=r'arn:aws(-[\w]+)*:[a-z0-9-\\.]{0,63}:[a-z0-9-\\.]{0,63}:[0-9]{12}:(\w|\/|-){1,1011}',
        min_length=1,
        max_length=1011,
    )


class AutoScalingConfigurationName(
    RootModel[
        constr(pattern=r'[A-Za-z0-9][A-Za-z0-9\-_]{3,31}', min_length=4, max_length=32)
    ]
):
    root: constr(
        pattern=r'[A-Za-z0-9][A-Za-z0-9\-_]{3,31}', min_length=4, max_length=32
    )


class AutoScalingConfigurationStatus(Enum):
    ACTIVE = 'ACTIVE'
    INACTIVE = 'INACTIVE'


class Boolean(RootModel[bool]):
    root: bool


class BuildCommand(RootModel[SecretStr]):
    root: SecretStr


class CertificateValidationRecordStatus(Enum):
    PENDING_VALIDATION = 'PENDING_VALIDATION'
    SUCCESS = 'SUCCESS'
    FAILED = 'FAILED'


class ConfigurationSource(Enum):
    REPOSITORY = 'REPOSITORY'
    API = 'API'


class ConnectionName(
    RootModel[
        constr(pattern=r'[A-Za-z0-9][A-Za-z0-9\-_]{3,31}', min_length=4, max_length=32)
    ]
):
    root: constr(
        pattern=r'[A-Za-z0-9][A-Za-z0-9\-_]{3,31}', min_length=4, max_length=32
    )


class ConnectionStatus(Enum):
    PENDING_HANDSHAKE = 'PENDING_HANDSHAKE'
    AVAILABLE = 'AVAILABLE'
    ERROR = 'ERROR'
    DELETED = 'DELETED'


class Cpu(
    RootModel[
        constr(
            pattern=r'256|512|1024|2048|4096|(0.25|0.5|1|2|4) vCPU',
            min_length=3,
            max_length=9,
        )
    ]
):
    root: constr(
        pattern=r'256|512|1024|2048|4096|(0.25|0.5|1|2|4) vCPU',
        min_length=3,
        max_length=9,
    )


class CustomDomainAssociationStatus(Enum):
    CREATING = 'CREATING'
    CREATE_FAILED = 'CREATE_FAILED'
    ACTIVE = 'ACTIVE'
    DELETING = 'DELETING'
    DELETE_FAILED = 'DELETE_FAILED'
    PENDING_CERTIFICATE_DNS_VALIDATION = 'PENDING_CERTIFICATE_DNS_VALIDATION'
    BINDING_CERTIFICATE = 'BINDING_CERTIFICATE'


class CustomerAccountId(
    RootModel[constr(pattern=r'[0-9]{12}', min_length=12, max_length=12)]
):
    root: constr(pattern=r'[0-9]{12}', min_length=12, max_length=12)


class DeleteAutoScalingConfigurationRequest(BaseModel):
    AutoScalingConfigurationArn: AppRunnerResourceArn


class DeleteConnectionRequest(BaseModel):
    ConnectionArn: AppRunnerResourceArn


class DeleteObservabilityConfigurationRequest(BaseModel):
    ObservabilityConfigurationArn: AppRunnerResourceArn


class DeleteServiceRequest(BaseModel):
    ServiceArn: AppRunnerResourceArn


class DeleteVpcConnectorRequest(BaseModel):
    VpcConnectorArn: AppRunnerResourceArn


class DeleteVpcIngressConnectionRequest(BaseModel):
    VpcIngressConnectionArn: AppRunnerResourceArn


class DescribeAutoScalingConfigurationRequest(BaseModel):
    AutoScalingConfigurationArn: AppRunnerResourceArn


class DescribeCustomDomainsMaxResults(RootModel[conint(ge=1, le=5)]):
    root: conint(ge=1, le=5)


class DescribeObservabilityConfigurationRequest(BaseModel):
    ObservabilityConfigurationArn: AppRunnerResourceArn


class DescribeServiceRequest(BaseModel):
    ServiceArn: AppRunnerResourceArn


class DescribeVpcConnectorRequest(BaseModel):
    VpcConnectorArn: AppRunnerResourceArn


class DescribeVpcIngressConnectionRequest(BaseModel):
    VpcIngressConnectionArn: AppRunnerResourceArn


class DomainName(
    RootModel[constr(pattern=r'[A-Za-z0-9*.-]{1,255}', min_length=1, max_length=255)]
):
    root: constr(pattern=r'[A-Za-z0-9*.-]{1,255}', min_length=1, max_length=255)


class EgressType(Enum):
    DEFAULT = 'DEFAULT'
    VPC = 'VPC'


class HealthCheckHealthyThreshold(RootModel[conint(ge=1, le=20)]):
    root: conint(ge=1, le=20)


class HealthCheckInterval(RootModel[conint(ge=1, le=20)]):
    root: conint(ge=1, le=20)


class HealthCheckPath(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class HealthCheckProtocol(Enum):
    TCP = 'TCP'
    HTTP = 'HTTP'


class HealthCheckTimeout(RootModel[conint(ge=1, le=20)]):
    root: conint(ge=1, le=20)


class HealthCheckUnhealthyThreshold(RootModel[conint(ge=1, le=20)]):
    root: conint(ge=1, le=20)


class ImageIdentifier(
    RootModel[
        constr(
            pattern=r'([0-9]{12}.dkr.ecr.[a-z\-]+-[0-9]{1}.amazonaws.com\/((?:[a-z0-9]+(?:[._-][a-z0-9]+)*\/)*[a-z0-9]+(?:[._-][a-z0-9]+)*)(:([\w\d+\-=._:\/@])+|@([\w\d\:]+))?)|(^public\.ecr\.aws\/.+\/((?:[a-z0-9]+(?:[._-][a-z0-9]+)*\/)*[a-z0-9]+(?:[._-][a-z0-9]+)*)(:([\w\d+\-=._:\/@])+|@([\w\d\:]+))?)',
            min_length=1,
            max_length=1024,
        )
    ]
):
    root: constr(
        pattern=r'([0-9]{12}.dkr.ecr.[a-z\-]+-[0-9]{1}.amazonaws.com\/((?:[a-z0-9]+(?:[._-][a-z0-9]+)*\/)*[a-z0-9]+(?:[._-][a-z0-9]+)*)(:([\w\d+\-=._:\/@])+|@([\w\d\:]+))?)|(^public\.ecr\.aws\/.+\/((?:[a-z0-9]+(?:[._-][a-z0-9]+)*\/)*[a-z0-9]+(?:[._-][a-z0-9]+)*)(:([\w\d+\-=._:\/@])+|@([\w\d\:]+))?)',
        min_length=1,
        max_length=1024,
    )


class ImageRepositoryType(Enum):
    ECR = 'ECR'
    ECR_PUBLIC = 'ECR_PUBLIC'


class IngressConfiguration(BaseModel):
    IsPubliclyAccessible: Optional[Boolean] = None


class Integer(RootModel[int]):
    root: int


class InternalServiceErrorException(RootModel[Any]):
    root: Any


class InvalidRequestException(RootModel[Any]):
    root: Any


class InvalidStateException(RootModel[Any]):
    root: Any


class KmsKeyArn(
    RootModel[
        constr(
            pattern=r'arn:aws(-[\w]+)*:kms:[a-z\-]+-[0-9]{1}:[0-9]{12}:key\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}',
            min_length=0,
            max_length=256,
        )
    ]
):
    root: constr(
        pattern=r'arn:aws(-[\w]+)*:kms:[a-z\-]+-[0-9]{1}:[0-9]{12}:key\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}',
        min_length=0,
        max_length=256,
    )


class ListOperationsMaxResults(RootModel[conint(ge=1, le=20)]):
    root: conint(ge=1, le=20)


class ListTagsForResourceRequest(BaseModel):
    ResourceArn: AppRunnerResourceArn


class MaxResults(RootModel[conint(ge=1, le=100)]):
    root: conint(ge=1, le=100)


class Memory(
    RootModel[
        constr(
            pattern=r'512|1024|2048|3072|4096|6144|8192|10240|12288|(0.5|1|2|3|4|6|8|10|12) GB',
            min_length=3,
            max_length=6,
        )
    ]
):
    root: constr(
        pattern=r'512|1024|2048|3072|4096|6144|8192|10240|12288|(0.5|1|2|3|4|6|8|10|12) GB',
        min_length=3,
        max_length=6,
    )


class NextToken(RootModel[constr(pattern=r'.*', min_length=1, max_length=1024)]):
    root: constr(pattern=r'.*', min_length=1, max_length=1024)


class NullableBoolean(RootModel[bool]):
    root: bool


class ObservabilityConfigurationName(
    RootModel[
        constr(pattern=r'[A-Za-z0-9][A-Za-z0-9\-_]{3,31}', min_length=4, max_length=32)
    ]
):
    root: constr(
        pattern=r'[A-Za-z0-9][A-Za-z0-9\-_]{3,31}', min_length=4, max_length=32
    )


class ObservabilityConfigurationStatus(Enum):
    ACTIVE = 'ACTIVE'
    INACTIVE = 'INACTIVE'


class ObservabilityConfigurationSummary(BaseModel):
    ObservabilityConfigurationArn: Optional[AppRunnerResourceArn] = None
    ObservabilityConfigurationName_1: Optional[ObservabilityConfigurationName] = Field(
        None, alias='ObservabilityConfigurationName'
    )
    ObservabilityConfigurationRevision: Optional[Integer] = None


class ObservabilityConfigurationSummaryList(
    RootModel[List[ObservabilityConfigurationSummary]]
):
    root: List[ObservabilityConfigurationSummary]


class OperationStatus(Enum):
    PENDING = 'PENDING'
    IN_PROGRESS = 'IN_PROGRESS'
    FAILED = 'FAILED'
    SUCCEEDED = 'SUCCEEDED'
    ROLLBACK_IN_PROGRESS = 'ROLLBACK_IN_PROGRESS'
    ROLLBACK_FAILED = 'ROLLBACK_FAILED'
    ROLLBACK_SUCCEEDED = 'ROLLBACK_SUCCEEDED'


class OperationType(Enum):
    START_DEPLOYMENT = 'START_DEPLOYMENT'
    CREATE_SERVICE = 'CREATE_SERVICE'
    PAUSE_SERVICE = 'PAUSE_SERVICE'
    RESUME_SERVICE = 'RESUME_SERVICE'
    DELETE_SERVICE = 'DELETE_SERVICE'
    UPDATE_SERVICE = 'UPDATE_SERVICE'


class PauseServiceRequest(BaseModel):
    ServiceArn: AppRunnerResourceArn


class ProviderType(Enum):
    GITHUB = 'GITHUB'


class ResourceNotFoundException(RootModel[Any]):
    root: Any


class ResumeServiceRequest(BaseModel):
    ServiceArn: AppRunnerResourceArn


class RoleArn(
    RootModel[
        constr(
            pattern=r'arn:(aws|aws-us-gov|aws-cn|aws-iso|aws-iso-b):iam::[0-9]{12}:(role|role\/service-role)\/[\w+=,.@\-/]{1,1000}',
            min_length=29,
            max_length=1024,
        )
    ]
):
    root: constr(
        pattern=r'arn:(aws|aws-us-gov|aws-cn|aws-iso|aws-iso-b):iam::[0-9]{12}:(role|role\/service-role)\/[\w+=,.@\-/]{1,1000}',
        min_length=29,
        max_length=1024,
    )


class Runtime(Enum):
    PYTHON_3 = 'PYTHON_3'
    NODEJS_12 = 'NODEJS_12'
    NODEJS_14 = 'NODEJS_14'
    CORRETTO_8 = 'CORRETTO_8'
    CORRETTO_11 = 'CORRETTO_11'
    NODEJS_16 = 'NODEJS_16'
    GO_1 = 'GO_1'
    DOTNET_6 = 'DOTNET_6'
    PHP_81 = 'PHP_81'
    RUBY_31 = 'RUBY_31'


class RuntimeEnvironmentSecretsName(RootModel[SecretStr]):
    root: SecretStr


class RuntimeEnvironmentSecretsValue(RootModel[SecretStr]):
    root: SecretStr


class RuntimeEnvironmentVariablesKey(RootModel[SecretStr]):
    root: SecretStr


class RuntimeEnvironmentVariablesValue(RootModel[SecretStr]):
    root: SecretStr


class ServiceId(
    RootModel[
        constr(
            pattern=r'[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}',
            min_length=32,
            max_length=32,
        )
    ]
):
    root: constr(
        pattern=r'[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}',
        min_length=32,
        max_length=32,
    )


class ServiceMaxResults(RootModel[conint(ge=1, le=20)]):
    root: conint(ge=1, le=20)


class ServiceName(
    RootModel[
        constr(pattern=r'[A-Za-z0-9][A-Za-z0-9-_]{3,39}', min_length=4, max_length=40)
    ]
):
    root: constr(pattern=r'[A-Za-z0-9][A-Za-z0-9-_]{3,39}', min_length=4, max_length=40)


class ServiceObservabilityConfiguration(BaseModel):
    ObservabilityConfigurationArn: Optional[AppRunnerResourceArn] = None
    ObservabilityEnabled: Boolean


class ServiceQuotaExceededException(RootModel[Any]):
    root: Any


class ServiceStatus(Enum):
    CREATE_FAILED = 'CREATE_FAILED'
    RUNNING = 'RUNNING'
    DELETED = 'DELETED'
    DELETE_FAILED = 'DELETE_FAILED'
    PAUSED = 'PAUSED'
    OPERATION_IN_PROGRESS = 'OPERATION_IN_PROGRESS'


class SourceCodeVersionType(Enum):
    BRANCH = 'BRANCH'


class StartCommand(RootModel[SecretStr]):
    root: SecretStr


class StartDeploymentRequest(BaseModel):
    ServiceArn: AppRunnerResourceArn


class String(RootModel[constr(pattern=r'.*', min_length=0, max_length=51200)]):
    root: constr(pattern=r'.*', min_length=0, max_length=51200)


class StringList(RootModel[List[String]]):
    root: List[String]


class TagKey(RootModel[constr(pattern=r'^(?!aws:).+', min_length=1, max_length=128)]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: constr(pattern=r'^(?!aws:).+', min_length=1, max_length=128)


class TagKeyList(RootModel[List[TagKey]]):
    root: List[TagKey]


class TagResourceResponse(BaseModel):
    pass


class TagValue(RootModel[constr(pattern=r'.*', min_length=0, max_length=256)]):
    root: constr(pattern=r'.*', min_length=0, max_length=256)


class Timestamp(RootModel[datetime]):
    root: datetime


class TracingVendor(Enum):
    AWSXRAY = 'AWSXRAY'


class UUID(
    RootModel[
        constr(
            pattern=r'[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}',
            min_length=36,
            max_length=36,
        )
    ]
):
    root: constr(
        pattern=r'[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}',
        min_length=36,
        max_length=36,
    )


class UntagResourceRequest(BaseModel):
    ResourceArn: AppRunnerResourceArn
    TagKeys: TagKeyList


class UntagResourceResponse(BaseModel):
    pass


class VpcConnectorName(
    RootModel[
        constr(pattern=r'[A-Za-z0-9][A-Za-z0-9\-_]{3,39}', min_length=4, max_length=40)
    ]
):
    root: constr(
        pattern=r'[A-Za-z0-9][A-Za-z0-9\-_]{3,39}', min_length=4, max_length=40
    )


class VpcConnectorStatus(Enum):
    ACTIVE = 'ACTIVE'
    INACTIVE = 'INACTIVE'


class VpcDNSTarget(BaseModel):
    DomainName_1: Optional[DomainName] = Field(None, alias='DomainName')
    VpcId: Optional[String] = None
    VpcIngressConnectionArn: Optional[AppRunnerResourceArn] = None


class VpcDNSTargetList(RootModel[List[VpcDNSTarget]]):
    root: List[VpcDNSTarget]


class VpcIngressConnectionName(
    RootModel[
        constr(pattern=r'[A-Za-z0-9][A-Za-z0-9\-_]{3,39}', min_length=4, max_length=40)
    ]
):
    root: constr(
        pattern=r'[A-Za-z0-9][A-Za-z0-9\-_]{3,39}', min_length=4, max_length=40
    )


class VpcIngressConnectionStatus(Enum):
    AVAILABLE = 'AVAILABLE'
    PENDING_CREATION = 'PENDING_CREATION'
    PENDING_UPDATE = 'PENDING_UPDATE'
    PENDING_DELETION = 'PENDING_DELETION'
    FAILED_CREATION = 'FAILED_CREATION'
    FAILED_UPDATE = 'FAILED_UPDATE'
    FAILED_DELETION = 'FAILED_DELETION'
    DELETED = 'DELETED'


class VpcIngressConnectionSummary(BaseModel):
    ServiceArn: Optional[AppRunnerResourceArn] = None
    VpcIngressConnectionArn: Optional[AppRunnerResourceArn] = None


class VpcIngressConnectionSummaryList(RootModel[List[VpcIngressConnectionSummary]]):
    root: List[VpcIngressConnectionSummary]


class XAmzTarget(Enum):
    AppRunner_AssociateCustomDomain = 'AppRunner.AssociateCustomDomain'


class XAmzTarget1(Enum):
    AppRunner_CreateAutoScalingConfiguration = (
        'AppRunner.CreateAutoScalingConfiguration'
    )


class XAmzTarget2(Enum):
    AppRunner_CreateConnection = 'AppRunner.CreateConnection'


class XAmzTarget3(Enum):
    AppRunner_CreateObservabilityConfiguration = (
        'AppRunner.CreateObservabilityConfiguration'
    )


class XAmzTarget4(Enum):
    AppRunner_CreateService = 'AppRunner.CreateService'


class XAmzTarget5(Enum):
    AppRunner_CreateVpcConnector = 'AppRunner.CreateVpcConnector'


class XAmzTarget6(Enum):
    AppRunner_CreateVpcIngressConnection = 'AppRunner.CreateVpcIngressConnection'


class XAmzTarget7(Enum):
    AppRunner_DeleteAutoScalingConfiguration = (
        'AppRunner.DeleteAutoScalingConfiguration'
    )


class XAmzTarget8(Enum):
    AppRunner_DeleteConnection = 'AppRunner.DeleteConnection'


class XAmzTarget9(Enum):
    AppRunner_DeleteObservabilityConfiguration = (
        'AppRunner.DeleteObservabilityConfiguration'
    )


class XAmzTarget10(Enum):
    AppRunner_DeleteService = 'AppRunner.DeleteService'


class XAmzTarget11(Enum):
    AppRunner_DeleteVpcConnector = 'AppRunner.DeleteVpcConnector'


class XAmzTarget12(Enum):
    AppRunner_DeleteVpcIngressConnection = 'AppRunner.DeleteVpcIngressConnection'


class XAmzTarget13(Enum):
    AppRunner_DescribeAutoScalingConfiguration = (
        'AppRunner.DescribeAutoScalingConfiguration'
    )


class XAmzTarget14(Enum):
    AppRunner_DescribeCustomDomains = 'AppRunner.DescribeCustomDomains'


class XAmzTarget15(Enum):
    AppRunner_DescribeObservabilityConfiguration = (
        'AppRunner.DescribeObservabilityConfiguration'
    )


class XAmzTarget16(Enum):
    AppRunner_DescribeService = 'AppRunner.DescribeService'


class XAmzTarget17(Enum):
    AppRunner_DescribeVpcConnector = 'AppRunner.DescribeVpcConnector'


class XAmzTarget18(Enum):
    AppRunner_DescribeVpcIngressConnection = 'AppRunner.DescribeVpcIngressConnection'


class XAmzTarget19(Enum):
    AppRunner_DisassociateCustomDomain = 'AppRunner.DisassociateCustomDomain'


class XAmzTarget20(Enum):
    AppRunner_ListAutoScalingConfigurations = 'AppRunner.ListAutoScalingConfigurations'


class XAmzTarget21(Enum):
    AppRunner_ListConnections = 'AppRunner.ListConnections'


class XAmzTarget22(Enum):
    AppRunner_ListObservabilityConfigurations = (
        'AppRunner.ListObservabilityConfigurations'
    )


class XAmzTarget23(Enum):
    AppRunner_ListOperations = 'AppRunner.ListOperations'


class XAmzTarget24(Enum):
    AppRunner_ListServices = 'AppRunner.ListServices'


class XAmzTarget25(Enum):
    AppRunner_ListTagsForResource = 'AppRunner.ListTagsForResource'


class XAmzTarget26(Enum):
    AppRunner_ListVpcConnectors = 'AppRunner.ListVpcConnectors'


class XAmzTarget27(Enum):
    AppRunner_ListVpcIngressConnections = 'AppRunner.ListVpcIngressConnections'


class XAmzTarget28(Enum):
    AppRunner_PauseService = 'AppRunner.PauseService'


class XAmzTarget29(Enum):
    AppRunner_ResumeService = 'AppRunner.ResumeService'


class XAmzTarget30(Enum):
    AppRunner_StartDeployment = 'AppRunner.StartDeployment'


class XAmzTarget31(Enum):
    AppRunner_TagResource = 'AppRunner.TagResource'


class XAmzTarget32(Enum):
    AppRunner_UntagResource = 'AppRunner.UntagResource'


class XAmzTarget33(Enum):
    AppRunner_UpdateService = 'AppRunner.UpdateService'


class XAmzTarget34(Enum):
    AppRunner_UpdateVpcIngressConnection = 'AppRunner.UpdateVpcIngressConnection'


class AssociateCustomDomainRequest(BaseModel):
    DomainName_1: DomainName = Field(..., alias='DomainName')
    EnableWWWSubdomain: Optional[NullableBoolean] = None
    ServiceArn: AppRunnerResourceArn


class AuthenticationConfiguration(BaseModel):
    AccessRoleArn: Optional[RoleArn] = None
    ConnectionArn: Optional[AppRunnerResourceArn] = None


class AutoScalingConfiguration(BaseModel):
    AutoScalingConfigurationArn: Optional[AppRunnerResourceArn] = None
    AutoScalingConfigurationName_1: Optional[AutoScalingConfigurationName] = Field(
        None, alias='AutoScalingConfigurationName'
    )
    AutoScalingConfigurationRevision: Optional[Integer] = None
    CreatedAt: Optional[Timestamp] = None
    DeletedAt: Optional[Timestamp] = None
    Latest: Optional[Boolean] = None
    MaxConcurrency: Optional[Integer] = None
    MaxSize: Optional[Integer] = None
    MinSize: Optional[Integer] = None
    Status: Optional[AutoScalingConfigurationStatus] = None


class AutoScalingConfigurationSummary(BaseModel):
    AutoScalingConfigurationArn: Optional[AppRunnerResourceArn] = None
    AutoScalingConfigurationName_1: Optional[AutoScalingConfigurationName] = Field(
        None, alias='AutoScalingConfigurationName'
    )
    AutoScalingConfigurationRevision: Optional[Integer] = None


class AutoScalingConfigurationSummaryList(
    RootModel[List[AutoScalingConfigurationSummary]]
):
    root: List[AutoScalingConfigurationSummary]


class CertificateValidationRecord(BaseModel):
    Name: Optional[String] = None
    Status: Optional[CertificateValidationRecordStatus] = None
    Type: Optional[String] = None
    Value: Optional[String] = None


class CertificateValidationRecordList(RootModel[List[CertificateValidationRecord]]):
    root: List[CertificateValidationRecord]


class Connection(BaseModel):
    ConnectionArn: Optional[AppRunnerResourceArn] = None
    ConnectionName_1: Optional[ConnectionName] = Field(None, alias='ConnectionName')
    CreatedAt: Optional[Timestamp] = None
    ProviderType_1: Optional[ProviderType] = Field(None, alias='ProviderType')
    Status: Optional[ConnectionStatus] = None


class ConnectionSummary(BaseModel):
    ConnectionArn: Optional[AppRunnerResourceArn] = None
    ConnectionName_1: Optional[ConnectionName] = Field(None, alias='ConnectionName')
    CreatedAt: Optional[Timestamp] = None
    ProviderType_1: Optional[ProviderType] = Field(None, alias='ProviderType')
    Status: Optional[ConnectionStatus] = None


class ConnectionSummaryList(RootModel[List[ConnectionSummary]]):
    root: List[ConnectionSummary]


class CreateAutoScalingConfigurationResponse(BaseModel):
    AutoScalingConfiguration_1: AutoScalingConfiguration = Field(
        ..., alias='AutoScalingConfiguration'
    )


class CreateConnectionResponse(BaseModel):
    Connection_1: Connection = Field(..., alias='Connection')


class CustomDomain(BaseModel):
    CertificateValidationRecords: Optional[CertificateValidationRecordList] = None
    DomainName_1: DomainName = Field(..., alias='DomainName')
    EnableWWWSubdomain: NullableBoolean
    Status: CustomDomainAssociationStatus


class CustomDomainList(RootModel[List[CustomDomain]]):
    root: List[CustomDomain]


class DeleteAutoScalingConfigurationResponse(BaseModel):
    AutoScalingConfiguration_1: AutoScalingConfiguration = Field(
        ..., alias='AutoScalingConfiguration'
    )


class DeleteConnectionResponse(BaseModel):
    Connection_1: Optional[Connection] = Field(None, alias='Connection')


class DescribeAutoScalingConfigurationResponse(BaseModel):
    AutoScalingConfiguration_1: AutoScalingConfiguration = Field(
        ..., alias='AutoScalingConfiguration'
    )


class DescribeCustomDomainsRequest(BaseModel):
    MaxResults: Optional[DescribeCustomDomainsMaxResults] = None
    NextToken: Optional[String] = None
    ServiceArn: AppRunnerResourceArn


class DescribeCustomDomainsResponse(BaseModel):
    CustomDomains: CustomDomainList
    DNSTarget: String
    NextToken: Optional[String] = None
    ServiceArn: AppRunnerResourceArn
    VpcDNSTargets: VpcDNSTargetList


class DisassociateCustomDomainRequest(BaseModel):
    DomainName_1: DomainName = Field(..., alias='DomainName')
    ServiceArn: AppRunnerResourceArn


class DisassociateCustomDomainResponse(BaseModel):
    CustomDomain_1: CustomDomain = Field(..., alias='CustomDomain')
    DNSTarget: String
    ServiceArn: AppRunnerResourceArn
    VpcDNSTargets: VpcDNSTargetList


class EgressConfiguration(BaseModel):
    EgressType_1: Optional[EgressType] = Field(None, alias='EgressType')
    VpcConnectorArn: Optional[AppRunnerResourceArn] = None


class EncryptionConfiguration(BaseModel):
    KmsKey: KmsKeyArn


class HealthCheckConfiguration(BaseModel):
    HealthyThreshold: Optional[HealthCheckHealthyThreshold] = None
    Interval: Optional[HealthCheckInterval] = None
    Path: Optional[HealthCheckPath] = None
    Protocol: Optional[HealthCheckProtocol] = None
    Timeout: Optional[HealthCheckTimeout] = None
    UnhealthyThreshold: Optional[HealthCheckUnhealthyThreshold] = None


class IngressVpcConfiguration(BaseModel):
    VpcEndpointId: Optional[String] = None
    VpcId: Optional[String] = None


class InstanceConfiguration(BaseModel):
    Cpu_1: Optional[Cpu] = Field(None, alias='Cpu')
    InstanceRoleArn: Optional[RoleArn] = None
    Memory_1: Optional[Memory] = Field(None, alias='Memory')


class ListAutoScalingConfigurationsRequest(BaseModel):
    AutoScalingConfigurationName_1: Optional[AutoScalingConfigurationName] = Field(
        None, alias='AutoScalingConfigurationName'
    )
    LatestOnly: Optional[Boolean] = None
    MaxResults_1: Optional[MaxResults] = Field(None, alias='MaxResults')
    NextToken_1: Optional[NextToken] = Field(None, alias='NextToken')


class ListAutoScalingConfigurationsResponse(BaseModel):
    AutoScalingConfigurationSummaryList_1: AutoScalingConfigurationSummaryList = Field(
        ..., alias='AutoScalingConfigurationSummaryList'
    )
    NextToken_1: Optional[NextToken] = Field(None, alias='NextToken')


class ListConnectionsRequest(BaseModel):
    ConnectionName_1: Optional[ConnectionName] = Field(None, alias='ConnectionName')
    MaxResults_1: Optional[MaxResults] = Field(None, alias='MaxResults')
    NextToken_1: Optional[NextToken] = Field(None, alias='NextToken')


class ListConnectionsResponse(BaseModel):
    ConnectionSummaryList_1: ConnectionSummaryList = Field(
        ..., alias='ConnectionSummaryList'
    )
    NextToken_1: Optional[NextToken] = Field(None, alias='NextToken')


class ListObservabilityConfigurationsRequest(BaseModel):
    LatestOnly: Optional[Boolean] = None
    MaxResults_1: Optional[MaxResults] = Field(None, alias='MaxResults')
    NextToken_1: Optional[NextToken] = Field(None, alias='NextToken')
    ObservabilityConfigurationName_1: Optional[ObservabilityConfigurationName] = Field(
        None, alias='ObservabilityConfigurationName'
    )


class ListObservabilityConfigurationsResponse(BaseModel):
    NextToken_1: Optional[NextToken] = Field(None, alias='NextToken')
    ObservabilityConfigurationSummaryList_1: ObservabilityConfigurationSummaryList = (
        Field(..., alias='ObservabilityConfigurationSummaryList')
    )


class ListOperationsRequest(BaseModel):
    MaxResults: Optional[ListOperationsMaxResults] = None
    NextToken: Optional[String] = None
    ServiceArn: AppRunnerResourceArn


class ListServicesRequest(BaseModel):
    MaxResults: Optional[ServiceMaxResults] = None
    NextToken: Optional[String] = None


class ListVpcConnectorsRequest(BaseModel):
    MaxResults_1: Optional[MaxResults] = Field(None, alias='MaxResults')
    NextToken_1: Optional[NextToken] = Field(None, alias='NextToken')


class ListVpcIngressConnectionsFilter(BaseModel):
    ServiceArn: Optional[AppRunnerResourceArn] = None
    VpcEndpointId: Optional[String] = None


class ListVpcIngressConnectionsRequest(BaseModel):
    Filter: Optional[ListVpcIngressConnectionsFilter] = None
    MaxResults_1: Optional[MaxResults] = Field(None, alias='MaxResults')
    NextToken_1: Optional[NextToken] = Field(None, alias='NextToken')


class ListVpcIngressConnectionsResponse(BaseModel):
    NextToken_1: Optional[NextToken] = Field(None, alias='NextToken')
    VpcIngressConnectionSummaryList_1: VpcIngressConnectionSummaryList = Field(
        ..., alias='VpcIngressConnectionSummaryList'
    )


class NetworkConfiguration(BaseModel):
    EgressConfiguration_1: Optional[EgressConfiguration] = Field(
        None, alias='EgressConfiguration'
    )
    IngressConfiguration_1: Optional[IngressConfiguration] = Field(
        None, alias='IngressConfiguration'
    )


class OperationSummary(BaseModel):
    EndedAt: Optional[Timestamp] = None
    Id: Optional[UUID] = None
    StartedAt: Optional[Timestamp] = None
    Status: Optional[OperationStatus] = None
    TargetArn: Optional[AppRunnerResourceArn] = None
    Type: Optional[OperationType] = None
    UpdatedAt: Optional[Timestamp] = None


class OperationSummaryList(RootModel[List[OperationSummary]]):
    root: List[OperationSummary]


class RuntimeEnvironmentSecrets(
    RootModel[Optional[Dict[str, RuntimeEnvironmentSecretsValue]]]
):
    root: Optional[Dict[str, RuntimeEnvironmentSecretsValue]] = None


class RuntimeEnvironmentVariables(
    RootModel[Optional[Dict[str, RuntimeEnvironmentVariablesValue]]]
):
    root: Optional[Dict[str, RuntimeEnvironmentVariablesValue]] = None


class ServiceSummary(BaseModel):
    CreatedAt: Optional[Timestamp] = None
    ServiceArn: Optional[AppRunnerResourceArn] = None
    ServiceId_1: Optional[ServiceId] = Field(None, alias='ServiceId')
    ServiceName_1: Optional[ServiceName] = Field(None, alias='ServiceName')
    ServiceUrl: Optional[String] = None
    Status: Optional[ServiceStatus] = None
    UpdatedAt: Optional[Timestamp] = None


class ServiceSummaryList(RootModel[List[ServiceSummary]]):
    root: List[ServiceSummary]


class SourceCodeVersion(BaseModel):
    Type: SourceCodeVersionType
    Value: String


class StartDeploymentResponse(BaseModel):
    OperationId: UUID


class Tag(BaseModel):
    Key: Optional[TagKey] = None
    Value: Optional[TagValue] = None


class TagList(RootModel[List[Tag]]):
    root: List[Tag]


class TagResourceRequest(BaseModel):
    ResourceArn: AppRunnerResourceArn
    Tags: TagList


class TraceConfiguration(BaseModel):
    Vendor: TracingVendor


class UpdateVpcIngressConnectionRequest(BaseModel):
    IngressVpcConfiguration_1: IngressVpcConfiguration = Field(
        ..., alias='IngressVpcConfiguration'
    )
    VpcIngressConnectionArn: AppRunnerResourceArn


class VpcConnector(BaseModel):
    CreatedAt: Optional[Timestamp] = None
    DeletedAt: Optional[Timestamp] = None
    SecurityGroups: Optional[StringList] = None
    Status: Optional[VpcConnectorStatus] = None
    Subnets: Optional[StringList] = None
    VpcConnectorArn: Optional[AppRunnerResourceArn] = None
    VpcConnectorName_1: Optional[VpcConnectorName] = Field(
        None, alias='VpcConnectorName'
    )
    VpcConnectorRevision: Optional[Integer] = None


class VpcConnectors(RootModel[List[VpcConnector]]):
    root: List[VpcConnector]


class VpcIngressConnection(BaseModel):
    AccountId: Optional[CustomerAccountId] = None
    CreatedAt: Optional[Timestamp] = None
    DeletedAt: Optional[Timestamp] = None
    DomainName_1: Optional[DomainName] = Field(None, alias='DomainName')
    IngressVpcConfiguration_1: Optional[IngressVpcConfiguration] = Field(
        None, alias='IngressVpcConfiguration'
    )
    ServiceArn: Optional[AppRunnerResourceArn] = None
    Status: Optional[VpcIngressConnectionStatus] = None
    VpcIngressConnectionArn: Optional[AppRunnerResourceArn] = None
    VpcIngressConnectionName_1: Optional[VpcIngressConnectionName] = Field(
        None, alias='VpcIngressConnectionName'
    )


class AssociateCustomDomainResponse(BaseModel):
    CustomDomain_1: CustomDomain = Field(..., alias='CustomDomain')
    DNSTarget: String
    ServiceArn: AppRunnerResourceArn
    VpcDNSTargets: VpcDNSTargetList


class CodeConfigurationValues(BaseModel):
    BuildCommand_1: Optional[BuildCommand] = Field(None, alias='BuildCommand')
    Port: Optional[String] = None
    Runtime_1: Runtime = Field(..., alias='Runtime')
    RuntimeEnvironmentSecrets_1: Optional[RuntimeEnvironmentSecrets] = Field(
        None, alias='RuntimeEnvironmentSecrets'
    )
    RuntimeEnvironmentVariables_1: Optional[RuntimeEnvironmentVariables] = Field(
        None, alias='RuntimeEnvironmentVariables'
    )
    StartCommand_1: Optional[StartCommand] = Field(None, alias='StartCommand')


class CreateAutoScalingConfigurationRequest(BaseModel):
    AutoScalingConfigurationName_1: AutoScalingConfigurationName = Field(
        ..., alias='AutoScalingConfigurationName'
    )
    MaxConcurrency: Optional[ASConfigMaxConcurrency] = None
    MaxSize: Optional[ASConfigMaxSize] = None
    MinSize: Optional[ASConfigMinSize] = None
    Tags: Optional[TagList] = None


class CreateConnectionRequest(BaseModel):
    ConnectionName_1: ConnectionName = Field(..., alias='ConnectionName')
    ProviderType_1: ProviderType = Field(..., alias='ProviderType')
    Tags: Optional[TagList] = None


class CreateObservabilityConfigurationRequest(BaseModel):
    ObservabilityConfigurationName_1: ObservabilityConfigurationName = Field(
        ..., alias='ObservabilityConfigurationName'
    )
    Tags: Optional[TagList] = None
    TraceConfiguration_1: Optional[TraceConfiguration] = Field(
        None, alias='TraceConfiguration'
    )


class CreateVpcConnectorRequest(BaseModel):
    SecurityGroups: Optional[StringList] = None
    Subnets: StringList
    Tags: Optional[TagList] = None
    VpcConnectorName_1: VpcConnectorName = Field(..., alias='VpcConnectorName')


class CreateVpcConnectorResponse(BaseModel):
    VpcConnector_1: VpcConnector = Field(..., alias='VpcConnector')


class CreateVpcIngressConnectionRequest(BaseModel):
    IngressVpcConfiguration_1: IngressVpcConfiguration = Field(
        ..., alias='IngressVpcConfiguration'
    )
    ServiceArn: AppRunnerResourceArn
    Tags: Optional[TagList] = None
    VpcIngressConnectionName_1: VpcIngressConnectionName = Field(
        ..., alias='VpcIngressConnectionName'
    )


class CreateVpcIngressConnectionResponse(BaseModel):
    VpcIngressConnection_1: VpcIngressConnection = Field(
        ..., alias='VpcIngressConnection'
    )


class DeleteVpcConnectorResponse(BaseModel):
    VpcConnector_1: VpcConnector = Field(..., alias='VpcConnector')


class DeleteVpcIngressConnectionResponse(BaseModel):
    VpcIngressConnection_1: VpcIngressConnection = Field(
        ..., alias='VpcIngressConnection'
    )


class DescribeVpcConnectorResponse(BaseModel):
    VpcConnector_1: VpcConnector = Field(..., alias='VpcConnector')


class DescribeVpcIngressConnectionResponse(BaseModel):
    VpcIngressConnection_1: VpcIngressConnection = Field(
        ..., alias='VpcIngressConnection'
    )


class ImageConfiguration(BaseModel):
    Port: Optional[String] = None
    RuntimeEnvironmentSecrets_1: Optional[RuntimeEnvironmentSecrets] = Field(
        None, alias='RuntimeEnvironmentSecrets'
    )
    RuntimeEnvironmentVariables_1: Optional[RuntimeEnvironmentVariables] = Field(
        None, alias='RuntimeEnvironmentVariables'
    )
    StartCommand_1: Optional[StartCommand] = Field(None, alias='StartCommand')


class ImageRepository(BaseModel):
    ImageConfiguration_1: Optional[ImageConfiguration] = Field(
        None, alias='ImageConfiguration'
    )
    ImageIdentifier_1: ImageIdentifier = Field(..., alias='ImageIdentifier')
    ImageRepositoryType_1: ImageRepositoryType = Field(..., alias='ImageRepositoryType')


class ListOperationsResponse(BaseModel):
    NextToken: Optional[String] = None
    OperationSummaryList_1: Optional[OperationSummaryList] = Field(
        None, alias='OperationSummaryList'
    )


class ListServicesResponse(BaseModel):
    NextToken: Optional[String] = None
    ServiceSummaryList_1: ServiceSummaryList = Field(..., alias='ServiceSummaryList')


class ListTagsForResourceResponse(BaseModel):
    Tags: Optional[TagList] = None


class ListVpcConnectorsResponse(BaseModel):
    NextToken_1: Optional[NextToken] = Field(None, alias='NextToken')
    VpcConnectors_1: VpcConnectors = Field(..., alias='VpcConnectors')


class ObservabilityConfiguration(BaseModel):
    CreatedAt: Optional[Timestamp] = None
    DeletedAt: Optional[Timestamp] = None
    Latest: Optional[Boolean] = None
    ObservabilityConfigurationArn: Optional[AppRunnerResourceArn] = None
    ObservabilityConfigurationName_1: Optional[ObservabilityConfigurationName] = Field(
        None, alias='ObservabilityConfigurationName'
    )
    ObservabilityConfigurationRevision: Optional[Integer] = None
    Status: Optional[ObservabilityConfigurationStatus] = None
    TraceConfiguration_1: Optional[TraceConfiguration] = Field(
        None, alias='TraceConfiguration'
    )


class UpdateVpcIngressConnectionResponse(BaseModel):
    VpcIngressConnection_1: VpcIngressConnection = Field(
        ..., alias='VpcIngressConnection'
    )


class CodeConfiguration(BaseModel):
    CodeConfigurationValues_1: Optional[CodeConfigurationValues] = Field(
        None, alias='CodeConfigurationValues'
    )
    ConfigurationSource_1: ConfigurationSource = Field(..., alias='ConfigurationSource')


class CodeRepository(BaseModel):
    CodeConfiguration_1: Optional[CodeConfiguration] = Field(
        None, alias='CodeConfiguration'
    )
    RepositoryUrl: String
    SourceCodeVersion_1: SourceCodeVersion = Field(..., alias='SourceCodeVersion')


class CreateObservabilityConfigurationResponse(BaseModel):
    ObservabilityConfiguration_1: ObservabilityConfiguration = Field(
        ..., alias='ObservabilityConfiguration'
    )


class DeleteObservabilityConfigurationResponse(BaseModel):
    ObservabilityConfiguration_1: ObservabilityConfiguration = Field(
        ..., alias='ObservabilityConfiguration'
    )


class DescribeObservabilityConfigurationResponse(BaseModel):
    ObservabilityConfiguration_1: ObservabilityConfiguration = Field(
        ..., alias='ObservabilityConfiguration'
    )


class SourceConfiguration(BaseModel):
    AuthenticationConfiguration_1: Optional[AuthenticationConfiguration] = Field(
        None, alias='AuthenticationConfiguration'
    )
    AutoDeploymentsEnabled: Optional[NullableBoolean] = None
    CodeRepository_1: Optional[CodeRepository] = Field(None, alias='CodeRepository')
    ImageRepository_1: Optional[ImageRepository] = Field(None, alias='ImageRepository')


class UpdateServiceRequest(BaseModel):
    AutoScalingConfigurationArn: Optional[AppRunnerResourceArn] = None
    HealthCheckConfiguration_1: Optional[HealthCheckConfiguration] = Field(
        None, alias='HealthCheckConfiguration'
    )
    InstanceConfiguration_1: Optional[InstanceConfiguration] = Field(
        None, alias='InstanceConfiguration'
    )
    NetworkConfiguration_1: Optional[NetworkConfiguration] = Field(
        None, alias='NetworkConfiguration'
    )
    ObservabilityConfiguration: Optional[ServiceObservabilityConfiguration] = None
    ServiceArn: AppRunnerResourceArn
    SourceConfiguration_1: Optional[SourceConfiguration] = Field(
        None, alias='SourceConfiguration'
    )


class CreateServiceRequest(BaseModel):
    AutoScalingConfigurationArn: Optional[AppRunnerResourceArn] = None
    EncryptionConfiguration_1: Optional[EncryptionConfiguration] = Field(
        None, alias='EncryptionConfiguration'
    )
    HealthCheckConfiguration_1: Optional[HealthCheckConfiguration] = Field(
        None, alias='HealthCheckConfiguration'
    )
    InstanceConfiguration_1: Optional[InstanceConfiguration] = Field(
        None, alias='InstanceConfiguration'
    )
    NetworkConfiguration_1: Optional[NetworkConfiguration] = Field(
        None, alias='NetworkConfiguration'
    )
    ObservabilityConfiguration: Optional[ServiceObservabilityConfiguration] = None
    ServiceName_1: ServiceName = Field(..., alias='ServiceName')
    SourceConfiguration_1: SourceConfiguration = Field(..., alias='SourceConfiguration')
    Tags: Optional[TagList] = None


class Service(BaseModel):
    AutoScalingConfigurationSummary_1: AutoScalingConfigurationSummary = Field(
        ..., alias='AutoScalingConfigurationSummary'
    )
    CreatedAt: Timestamp
    DeletedAt: Optional[Timestamp] = None
    EncryptionConfiguration_1: Optional[EncryptionConfiguration] = Field(
        None, alias='EncryptionConfiguration'
    )
    HealthCheckConfiguration_1: Optional[HealthCheckConfiguration] = Field(
        None, alias='HealthCheckConfiguration'
    )
    InstanceConfiguration_1: InstanceConfiguration = Field(
        ..., alias='InstanceConfiguration'
    )
    NetworkConfiguration_1: NetworkConfiguration = Field(
        ..., alias='NetworkConfiguration'
    )
    ObservabilityConfiguration: Optional[ServiceObservabilityConfiguration] = None
    ServiceArn: AppRunnerResourceArn
    ServiceId_1: ServiceId = Field(..., alias='ServiceId')
    ServiceName_1: ServiceName = Field(..., alias='ServiceName')
    ServiceUrl: Optional[String] = None
    SourceConfiguration_1: SourceConfiguration = Field(..., alias='SourceConfiguration')
    Status: ServiceStatus
    UpdatedAt: Timestamp


class UpdateServiceResponse(BaseModel):
    OperationId: UUID
    Service_1: Service = Field(..., alias='Service')


class CreateServiceResponse(BaseModel):
    OperationId: UUID
    Service_1: Service = Field(..., alias='Service')


class DeleteServiceResponse(BaseModel):
    OperationId: UUID
    Service_1: Service = Field(..., alias='Service')


class DescribeServiceResponse(BaseModel):
    Service_1: Service = Field(..., alias='Service')


class PauseServiceResponse(BaseModel):
    OperationId: Optional[UUID] = None
    Service_1: Service = Field(..., alias='Service')


class ResumeServiceResponse(BaseModel):
    OperationId: Optional[UUID] = None
    Service_1: Service = Field(..., alias='Service')
